Feature/forms branch finished
ricardovaltierra/re-former pull request #2
Opened 2020-02-12 20:35 UTC by ricardovaltierra

The following features where added:

- Back End set up
  * Create User model w/ username, email and password
  * Migrate db
  * Validations for presence
  * Views created for 'new' and 'edit' actions with `form_for`

2020-02-12 23:48 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello @ricardovaltierra @ClintonEnyinna 

Everything is almost OK except the forms.
According to [that](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form1.png), [that one too](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form2.png), and [this last one](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form_tag2.png), you need to implement the form. 
And after doing it, you have to comment them except the last one. We will check the commented code.
You have to do it form `new` and `edit` path.

Kindly make the suggested changes and submit a new code review request
Thanks

Mael FOSSO

2020-02-13 19:59 UTC, samgaco approved these changes
Hi @ricardovaltierra and @ClintonEnyinna :high_brightness: 

I left some comments below some fixes you should handle before merging.

The project is approved :+1: 

-------------------------

* ###### STATUS OF THE PROJECT: APPROVED :heavy_check_mark:

2020-02-13 19:59 UTC, samgaco commented on app/views/users/edit.html.erb
> +  <br>
this should be commented too

2020-02-13 19:59 UTC, samgaco commented on app/views/users/new.html.erb
> +  <br>
should be commented

2020-02-13 20:09 UTC, merged